### ISSUE TITLE
FormEditor v0.11.1.1 ~ System.Reflection.ReflectionTypeLoadException Error

### ISSUE THREAD

**Issue by jonrandahl** [kjac/FormEditor#180] opened 2018-03-08 00:14 UTC
Ken,

First, belated congratulations on working at HQ! I'll have to find you in May to say hello!

Second, apologies for requesting support for such an old version however at this moment the upgrade path is not feasible at this time as both the dev and staging sites are running on v7.5.11. 

Finally, the issue is that no matter what I do I cannot get the fields to render in the back office? I've tried saving every data type in the back office again - (3 x so far), I've created new form editor data types which works fine until I save and then the error is triggered on the reload, as well as uninstalled and reinstalled the required package version .. twice!

The error is not logged in the Trace Logs, which is severely dampening my attempts to resolve this on my own!

As soon as I browse/create a Form Module DataType, I receive this error:

```
 Received an error from the server
An error occured
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

EXCEPTION DETAILS
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
STACKTRACE
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at FormEditor.Api.PropertyEditorController.<>c__DisplayClassa`1.<GetInstancesOf>b__7(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FormEditor.Api.PropertyEditorController.GetInstancesOf[T](Type[] ignoredTypes)
   at FormEditor.Api.PropertyEditorController.GetAllFieldTypes()
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

I'm happy to give you access to the staging server where you can see this in action however I will need to manage that via direct message of course!

Thank you for your time and patience and again please accept my congratulations!

Kind regards,
Jon

**Comment by kjac** [comment] 2018-03-08 08:53
Hi @jonrandahl,

Why thank you! Though last I checked I wasn't employed at HQ, but I guess I'll have to do a double check 😉 

What you're experiencing could be caused by a multitude of things. Since I can't see the LoaderExceptions I've no idea where to start, really. 

My only suggestion at this point is for you to download the [original source for v0.11.1.1](https://github.com/kjac/FormEditor/releases/tag/v0.11.1.1-beta), build it, attach the debugger to your site and set a breakpoint in `FormEditor.Api.PropertyEditorController.GetAllFieldTypes()`. Hopefully you can find a clue as to what's going on by inspecting the exception that's thrown.

**Comment by jonrandahl** [comment] 2018-03-08 11:18
Ken, I feel really sheepish now... this isn't you then? 

https://umbraco.com/blog/new-hire-at-umbraco-hq-kenneth-jakobsen/ #doh!

I'll pull the source down and do exactly that, thank you!

#jongoesoffhanginghisheadinshame

**Comment by kjac** [comment] 2018-03-08 12:15
@jonrandahl haha no that's not me. Name is pretty darn close, tho'!

Let me know how you get along with the troubleshooting.

**Comment by kjac** [comment] 2018-04-30 19:29
I'm closing this now :)

**Closed by kjac** 2018-04-30 19:29 UTC
