### ISSUE TITLE
File upload doesn't work

### ISSUE THREAD

**Issue by bobi33** [kjac/FormEditor#126] opened 2017-04-09 01:36 UTC
I've set the file upload to allow 1mb of data and PNG, but for some reason on form submit I constantly get an error message re the file upload...I'm not sure why this is happening.

**Comment by kjac** [comment] 2017-04-09 06:31
Hi @bobi33,

Thanks for reporting. I can recreate the issue... I'll look into it and fix it in the upcoming release (should be imminent).

**Comment by bobi33** [comment] 2017-04-09 20:56
Hi @kjac, thanks for the response :)

I figured out what was happening...file size wasn't too accurate. I'll close this one, but keep an eye out because I thought I set it correctly...although it was quite late in the day, so perhaps it was my eyes.

Thanks.

**Comment by kjac** [comment] 2017-04-10 09:55
Hi @bobi33,

The issue is very real. The problem (or at least one of them) is that when you configure the upload field, you're asked to enter the max size in kilobytes... but when the upload field validates the uploaded file, it believes this max size is entered in bytes. I've got that fixed, and will re-test the issue as soon as I can.

**Comment by kjac** [comment] 2017-04-10 18:14
There... the fix will be in the next release, which should be pretty imminent.

**Closed** 2017-04-10 18:14 UTC
