### ISSUE TITLE
Installed on a clean 7.4.1 (on UAAS)

### ISSUE THREAD

**Issue by jesperordrup** [kjac/FormEditor#28] opened 2016-04-12 18:33 UTC
Installed Umbraco 7.4.1 (pull from UAAS)
Installed FormEditor via nuget
Started website 

This happens:

![screen shot 2016-04-12 at 15 54 59](https://cloud.githubusercontent.com/assets/3120151/14464213/3c2ff8c6-00ce-11e6-9d77-faf575c61958.png)

**Comment by kjac** [comment] 2016-04-12 18:44
Hi @jesperordrup,

I haven't had time to implement UaaS support in FormEditor yet. What you're seeing is pretty much what I'd expect to see on UaaS :)

It's on my TODO list.

**Comment by jesperordrup** [comment] 2016-04-12 20:06
It seems to work on UAAS if you just install as an umbraco package .. both locally and on Azure

**Comment by kjac** [comment] 2016-04-12 20:26
Oooh.... right. Then I think I know what the problem is; FormEditor has a dependency on Umbraco core binaries v7.3, because it's compatible with 7.3+. 

I've actually made a note of it in the "extending FormEditor" docs [here](https://github.com/kjac/FormEditor/blob/master/Docs/extend_field_advanced.md#project-output) (although that was not meant as a comment specifically for UaaS).

All the same, UaaS support is on the drawing board - including finding the best way to actually support UaaS, be it nuget or package installs or whatnot. But thanks a lot for reporting and making me aware of the problem.

**Comment by kjac** [comment] 2016-04-20 15:32
Hey Jesper, did you solve the issue by installing the package by hand?

**Comment by jesperordrup** [comment] 2016-04-20 15:59
Yup - downloaded the Umbraco Package and installed it via Developer section

**Comment by kjac** [comment] 2016-05-09 05:38
Closing this for now. I might have to revisit UaaS stuff later on.

**Closed by kjac** 2016-05-09 05:38 UTC
